### ISSUE TITLE
Capstone Group

### ISSUE THREAD

**Issue by raminka13** [Nyame-Wolf/ruby-catalog#5]
[Ruby Catalog Repository](https://github.com/Nyame-Wolf/ruby-catalog/projects/1)
Our group is 3 members:
- Team member 1: @raminka13
- Team member 2: @Nyame-Wolf 
- Team member 3: @Fourteen98

**Comment by mukhammadrizooff** [comment]
Hi @TEAM, 

In my opinion, your project is ready for the presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

<img src="https://media3.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif"/>

Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**Comment by raminka13** [comment]
Thanks a lot.
